name: Sonar Scanner for project
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code repo
      uses: actions/checkout@v4
    - name: Setup node & npm
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install packages
      run: |
        cd Frontend
        npm install
        npm run build
        cd ..
    - name: setup java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "21"
    - name: Install Maven
      run: sudo apt-get install -y maven
    - name: Build project with Maven
      run: |
        cd BackendSpringBoot
        mvn clean install -DskipTests
        cd ..
  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SonarQube Scan for react
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: Frontend/
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    - name: SonarQube Scan for java
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: BackendSpringBoot/
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
